// CodeMind Code Lab — Curriculum
// Each lesson has: concept explanation, starter code, expected output check, hints

export type LessonTier = 'EXPLORER' | 'BUILDER' | 'CREATOR'
export type LessonSubject = 'coding' | 'math'

export interface Lesson {
  id: string
  tier: LessonTier
  subject: LessonSubject  // 'coding' | 'math'
  unit: string           // e.g. "Variables"
  unitIndex: number      // order within unit
  title: string
  emoji: string
  realWorldUse: string   // one-liner: "Used in: ..."
  concept: string        // plain-language explanation of the concept
  example: string        // annotated example shown before the challenge
  challenge: string      // what the child must do
  starterCode: string    // pre-filled in editor
  solutionCode: string   // reference solution (not shown to child)
  checkOutput: (output: string) => boolean  // validates their output
  expectedHint: string   // what the output should look like
  hints: string[]
}

// ── EXPLORER (4–7): Scratch-style, very simple Python with output ─────────────

const EXPLORER_LESSONS: Lesson[] = [
  // ── CODING ───────────────────────────────────────────────────────────────────
  {
    id: 'exp-1-1',
    tier: 'EXPLORER',
    subject: 'coding',
    unit: 'Say Hello',
    unitIndex: 0,
    title: 'Make the computer talk!',
    emoji: '👋',
    realWorldUse: 'Used in: apps, games, and every program ever made',
    concept: `Computers can say words! We use a special command called **print()** to make the computer write something on the screen.\n\nPut words inside the brackets, and wrap them in "speech marks" like this:\n\n\`print("Hello!")\``,
    example: `print("Hello, world!")`,
    challenge: `Make the computer say **"Hello, I love coding!"**\n\nChange the words inside the speech marks!`,
    starterCode: `print("Hello, ___!")`,
    solutionCode: `print("Hello, I love coding!")`,
    checkOutput: (o) => o.toLowerCase().includes('hello'),
    expectedHint: 'Something starting with Hello',
    hints: [
      'Replace the ___ with your message',
      'Make sure you keep the speech marks " " around your words',
      'Try: print("Hello, I love coding!")',
    ],
  },
  {
    id: 'exp-1-2',
    tier: 'EXPLORER',
    subject: 'coding',
    unit: 'Say Hello',
    unitIndex: 1,
    title: 'Make a robot introduction!',
    emoji: '🤖',
    realWorldUse: 'Used in: chatbots, game characters, virtual assistants',
    concept: `You can make the computer say MULTIPLE things — one print() per line!\n\n\`print("Hi!")\nprint("I am a robot")\`\n\nEach print() goes on a new line.`,
    example: `print("Beep boop!")\nprint("I am Robot-3000")\nprint("Nice to meet you!")`,
    challenge: `Make a robot introduce itself with **3 lines**:\n1. A robot sound (like "Beep boop!")\n2. Its name\n3. A greeting`,
    starterCode: `print("___")\nprint("___")\nprint("___")`,
    solutionCode: `print("Beep boop!")\nprint("I am Robot-3000")\nprint("Nice to meet you!")`,
    checkOutput: (o) => o.trim().split('\n').length >= 3,
    expectedHint: '3 lines — a sound, a name, and a greeting',
    hints: [
      'First line: make a robot sound like "Beep boop!"',
      'Second line: give the robot a name',
      'Third line: say hello!',
    ],
  },
  {
    id: 'exp-3-1',
    tier: 'EXPLORER',
    subject: 'coding',
    unit: 'Repeat',
    unitIndex: 0,
    title: 'Say it 3 times!',
    emoji: '🔁',
    realWorldUse: 'Used in: sending notifications, drawing patterns, game animations',
    concept: `What if you want to say the same thing lots of times? You could write print() over and over... or use a **loop**!\n\nA loop repeats code for you:\n\n\`for i in range(3):\n    print("Woof!")\`\n\nThis prints "Woof!" **3 times**. The number in range() controls how many times!`,
    example: `for i in range(3):\n    print("Hello!")`,
    challenge: `Make the computer print **"I love coding!"** exactly **5 times** using a loop!`,
    starterCode: `for i in range(___):\n    print("I love coding!")`,
    solutionCode: `for i in range(5):\n    print("I love coding!")`,
    checkOutput: (o) => o.split('\n').filter(l => l.includes('I love coding')).length === 5,
    expectedHint: 'I love coding! (printed 5 times)',
    hints: [
      'Change the ___ to the number of times you want to repeat',
      'You want it 5 times, so put 5 in range()',
      'Try: for i in range(5):',
    ],
  },

  // ── MATH ─────────────────────────────────────────────────────────────────────
  {
    id: 'exp-m-1-1',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Numbers',
    unitIndex: 0,
    title: 'Count your toys!',
    emoji: '🧸',
    realWorldUse: 'Used in: shopping totals, score counters, inventory apps',
    concept: `Computers are amazing at maths! You can add numbers using the **+** sign.\n\nYou don't need speech marks for numbers — just write them!\n\n\`print(2 + 3)\`\n\nThis will print **5**.`,
    example: `print("I have", 3 + 2, "toys")`,
    challenge: `You have **5 red blocks** and **4 blue blocks**. Use code to find the total!\n\nPrint: \`"Total blocks:", answer\``,
    starterCode: `print("Total blocks:", ___ + ___)`,
    solutionCode: `print("Total blocks:", 5 + 4)`,
    checkOutput: (o) => o.includes('9'),
    expectedHint: 'Total blocks: 9',
    hints: [
      'Add 5 red blocks and 4 blue blocks',
      '5 + 4 = 9',
      'Try: print("Total blocks:", 5 + 4)',
    ],
  },
  {
    id: 'exp-m-1-2',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Numbers',
    unitIndex: 1,
    title: 'Rocket countdown!',
    emoji: '🚀',
    realWorldUse: 'Used in: game timers, launch sequences, event countdowns',
    concept: `You can print lots of things one after another — just use multiple **print()** lines!\n\nEach print goes on its own line.`,
    example: `print(3)\nprint(2)\nprint(1)\nprint("Blast off!")`,
    challenge: `Make a **rocket countdown** from 5 to 1, then print "Blast off!"\n\nThat's 6 lines total!`,
    starterCode: `print(5)\nprint(4)\nprint(___)\nprint(___)\nprint(___)\nprint("___")`,
    solutionCode: `print(5)\nprint(4)\nprint(3)\nprint(2)\nprint(1)\nprint("Blast off!")`,
    checkOutput: (o) => ['5','4','3','2','1'].every(n => o.includes(n)) && o.toLowerCase().includes('blast'),
    expectedHint: '5 4 3 2 1 Blast off!',
    hints: [
      'Count down: 3, 2, 1',
      'The last line should say "Blast off!"',
    ],
  },
  {
    id: 'exp-m-2-1',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Shapes',
    unitIndex: 0,
    title: 'Count the sides of a shape!',
    emoji: '🔺',
    realWorldUse: 'Used in: game graphics, building design, art apps',
    concept: `Shapes have sides! A triangle has **3 sides**. A square has **4 sides**. A pentagon has **5 sides**.\n\nWe can use code to print facts about shapes!`,
    example: `print("A triangle has 3 sides")\nprint("A square has 4 sides")`,
    challenge: `Print the number of sides for:\n- A triangle (3)\n- A square (4)\n- A pentagon (5)\n- A hexagon (6)`,
    starterCode: `print("Triangle:", ___)\nprint("Square:", ___)\nprint("Pentagon:", ___)\nprint("Hexagon:", ___)`,
    solutionCode: `print("Triangle:", 3)\nprint("Square:", 4)\nprint("Pentagon:", 5)\nprint("Hexagon:", 6)`,
    checkOutput: (o) => o.includes('3') && o.includes('4') && o.includes('5') && o.includes('6'),
    expectedHint: 'Triangle: 3 / Square: 4 / Pentagon: 5 / Hexagon: 6',
    hints: [
      'A triangle has 3 sides — put 3 after the comma',
      'A square has 4, pentagon has 5, hexagon has 6',
    ],
  },
  {
    id: 'exp-2-1',
    tier: 'EXPLORER',
    subject: 'coding',
    unit: 'Say Hello',
    unitIndex: 2,
    title: 'Draw with code!',
    emoji: '🎨',
    realWorldUse: 'Used in: ASCII art, game graphics, terminal interfaces',
    concept: `You can draw pictures using text characters! Each print() is one line of your picture.\n\n\`print("  *  ")\nprint(" *** ")\nprint("*****")\`\n\nThis draws a triangle!`,
    example: `print("  O  ")\nprint(" /|\\ ")\nprint(" / \\ ")\nprint("A person!")`,
    challenge: `Draw a **tree** using text characters:\n1. Print a star: "  *  "\n2. Print branches: " *** "\n3. Print more branches: "*****"\n4. Print the trunk: "  |  "`,
    starterCode: `print("  *  ")\nprint(" ___ ")\nprint("_____")\nprint(" ___ ")`,
    solutionCode: `print("  *  ")\nprint(" *** ")\nprint("*****")\nprint("  |  ")`,
    checkOutput: (o) => o.includes('*') && o.includes('|'),
    expectedHint: 'A tree made of stars and a trunk',
    hints: [
      'Line 2: three stars with spaces: " *** "',
      'Line 3: five stars: "*****"',
      'Line 4: the trunk is a pipe: "  |  "',
    ],
  },
  {
    id: 'exp-4-1',
    tier: 'EXPLORER',
    subject: 'coding',
    unit: 'Repeat',
    unitIndex: 1,
    title: 'Build a staircase!',
    emoji: '🪜',
    realWorldUse: 'Used in: progress bars, level indicators, loading screens',
    concept: `You can use the loop number \`i\` to make things that GROW!\n\n\`for i in range(3):\n    print(i)\`\n\nThis prints 0, 1, 2 — the number changes each time!`,
    example: `for i in range(4):\n    print(i)`,
    challenge: `Use a loop to print numbers from 1 to 5 (or 0 to 4 — both work!).`,
    starterCode: `for i in range(___):\n    print(i)`,
    solutionCode: `for i in range(1, 6):\n    print(i)`,
    checkOutput: (o) => {
      const has0to4 = ['0','1','2','3','4'].every(n => o.includes(n))
      const has1to5 = ['1','2','3','4','5'].every(n => o.includes(n))
      return has0to4 || has1to5
    },
    expectedHint: '0 1 2 3 4 or 1 2 3 4 5 (each on its own line)',
    hints: [
      'You can use range(5) for 0–4, or range(1, 6) for 1–5',
      'Both answers are correct!',
    ],
  },
  {
    id: 'exp-4-2',
    tier: 'EXPLORER',
    subject: 'coding',
    unit: 'Repeat',
    unitIndex: 2,
    title: 'Animal parade!',
    emoji: '🐾',
    realWorldUse: 'Used in: game character spawning, batch processing, animations',
    concept: `You can print different things inside a loop! Use the loop number to pick different items.\n\nBut for now, let's keep it simple — print the same fun thing lots of times!`,
    example: `for i in range(4):\n    print("Meow!")`,
    challenge: `Make an animal parade! Print **"🐘"** (elephant emoji) exactly **6 times** using a loop!`,
    starterCode: `for i in range(___):\n    print("___")`,
    solutionCode: `for i in range(6):\n    print("🐘")`,
    checkOutput: (o) => o.split('\n').filter(l => l.includes('🐘')).length >= 6,
    expectedHint: '🐘 (printed 6 times)',
    hints: [
      'Put 6 in range() for 6 times',
      'Put the elephant emoji 🐘 in the speech marks',
    ],
  },
  {
    id: 'exp-m-3-1',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Numbers',
    unitIndex: 2,
    title: 'How many are left?',
    emoji: '🍪',
    realWorldUse: 'Used in: inventory tracking, bank balances, game lives',
    concept: `You can subtract using the **-** sign!\n\n\`print(10 - 3)\`\n\nThis prints **7**.`,
    example: `print("I had 20 cookies, ate 8:")\nprint(20 - 8, "left!")`,
    challenge: `You had **15 candies** and gave **7** to a friend. How many do you have left?\n\nPrint: \`"Candies left:", answer\``,
    starterCode: `print("Candies left:", ___ - ___)`,
    solutionCode: `print("Candies left:", 15 - 7)`,
    checkOutput: (o) => o.includes('8'),
    expectedHint: 'Candies left: 8',
    hints: [
      'Start with 15, subtract 7',
      '15 - 7 = 8',
    ],
  },
  {
    id: 'exp-m-3-2',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Numbers',
    unitIndex: 3,
    title: 'Count legs in the farm!',
    emoji: '🐄',
    realWorldUse: 'Used in: shopping totals, recipe scaling, bulk ordering',
    concept: `You can multiply using the **\*** sign (that's a star in code)!\n\n\`print(3 * 4)\`\n\nThis prints **12**.`,
    example: `print("3 cows have", 3 * 4, "legs")`,
    challenge: `A farm has **6 horses**. Each horse has **4 legs**. How many legs total?\n\nPrint: \`"Total legs:", answer\``,
    starterCode: `print("Total legs:", ___ * ___)`,
    solutionCode: `print("Total legs:", 6 * 4)`,
    checkOutput: (o) => o.includes('24'),
    expectedHint: 'Total legs: 24',
    hints: [
      '6 horses × 4 legs each',
      '6 × 4 = 24',
    ],
  },
  {
    id: 'exp-m-4-1',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Shapes',
    unitIndex: 1,
    title: 'Count corners!',
    emoji: '📐',
    realWorldUse: 'Used in: 3D game design, CAD software, robotics',
    concept: `Shapes have corners too! A triangle has **3 corners**. A square has **4 corners**.\n\nThe number of corners = the number of sides!`,
    example: `print("A triangle has 3 corners")\nprint("A square has 4 corners")`,
    challenge: `Print the number of corners for a triangle, square, pentagon, and hexagon.`,
    starterCode: `print("Triangle:", ___)\nprint("Square:", ___)\nprint("Pentagon:", ___)\nprint("Hexagon:", ___)`,
    solutionCode: `print("Triangle:", 3)\nprint("Square:", 4)\nprint("Pentagon:", 5)\nprint("Hexagon:", 6)`,
    checkOutput: (o) => o.includes('3') && o.includes('4') && o.includes('5') && o.includes('6'),
    expectedHint: 'Triangle: 3 / Square: 4 / Pentagon: 5 / Hexagon: 6',
    hints: [
      'Corners = sides for these shapes',
      'Triangle=3, Square=4, Pentagon=5, Hexagon=6',
    ],
  },
  {
    id: 'exp-m-5-1',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Patterns',
    unitIndex: 0,
    title: 'Build a pyramid!',
    emoji: '🏛️',
    realWorldUse: 'Used in: creating art with code, game design, data visualisation',
    concept: `You can make patterns with code! Use a loop to print the same thing over and over.\n\n\`for i in range(3):\n    print("*")\`\n\nThis prints three stars!`,
    example: `for i in range(5):\n    print("*")`,
    challenge: `Use a loop to print **10 stars** (one on each line) — build a tall tower!`,
    starterCode: `for i in range(___):\n    print("___")`,
    solutionCode: `for i in range(10):\n    print("*")`,
    checkOutput: (o) => o.split('\n').filter(l => l.includes('*')).length >= 10,
    expectedHint: '10 stars, each on its own line',
    hints: [
      'Put 10 in range()',
      'Put * in the speech marks',
    ],
  },
  {
    id: 'exp-m-5-2',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Patterns',
    unitIndex: 1,
    title: 'Times table with a loop!',
    emoji: '✖️',
    realWorldUse: 'Used in: data visualisation, multiplication tables, math apps',
    concept: `You can use the loop number \`i\` to do maths that changes each time!\n\n\`for i in range(3):\n    print(i * 2)\`\n\nThis prints 0, 2, 4 — the 2 times table!`,
    example: `for i in range(5):\n    print(i * 2)`,
    challenge: `Print the **3 times table** from 0 to 5:\n0×3=0, 1×3=3, 2×3=6, 3×3=9, 4×3=12, 5×3=15`,
    starterCode: `for i in range(___):\n    print(i * ___)`,
    solutionCode: `for i in range(6):\n    print(i * 3)`,
    checkOutput: (o) => o.includes('0') && o.includes('3') && o.includes('9') && o.includes('15'),
    expectedHint: '0 3 6 9 12 15',
    hints: [
      'range(6) gives 0 through 5',
      'Multiply by 3 for the 3 times table',
    ],
  },
  {
    id: 'exp-5-1',
    tier: 'EXPLORER',
    subject: 'coding',
    unit: 'Variables',
    unitIndex: 0,
    title: 'Save a secret number!',
    emoji: '🔮',
    realWorldUse: 'Used in: saving game scores, storing settings, remembering choices',
    concept: `A **variable** saves something for later! Give it a name and put a value in it.\n\n\`score = 100\nprint(score)\`\n\nThe computer remembers what score is!`,
    example: `magic_number = 42\nprint("The secret number is", magic_number)`,
    challenge: `Save a **secret number** in a variable called \`magic\`, then print it with a message!\n\nMake your message: \`"My magic number is:", magic\``,
    starterCode: `magic = ___\nprint("My magic number is:", ___)`,
    solutionCode: `magic = 42\nprint("My magic number is:", magic)`,
    checkOutput: (o) => o.includes('magic number'),
    expectedHint: 'My magic number is: [your number]',
    hints: [
      'Pick any number for magic',
      'Print the variable magic (no speech marks around it!)',
    ],
  },
  {
    id: 'exp-m-6-1',
    tier: 'EXPLORER',
    subject: 'math',
    unit: 'Numbers',
    unitIndex: 4,
    title: 'Share the pizza!',
    emoji: '🍕',
    realWorldUse: 'Used in: splitting bills, sharing resources, team assignments',
    concept: `Division means sharing! Use the **/** sign.\n\n\`print(10 / 2)\`\n\nThis prints **5.0** — 10 shared between 2 people = 5 each!`,
    example: `print("12 sweets shared by 3:", 12 / 3, "each")`,
    challenge: `You have **24 slices of pizza** and **6 friends**. How many slices does each friend get?\n\nPrint: \`"Each friend gets:", answer, "slices"\``,
    starterCode: `print("Each friend gets:", ___ / ___, "slices")`,
    solutionCode: `print("Each friend gets:", 24 / 6, "slices")`,
    checkOutput: (o) => o.includes('4'),
    expectedHint: 'Each friend gets: 4.0 slices',
    hints: [
      '24 slices divided by 6 friends',
      '24 / 6 = 4',
    ],
  },
]

// ── BUILDER (8–11): Real Python concepts + real math ────────────────────────

const BUILDER_LESSONS: Lesson[] = [
  // ── CODING ───────────────────────────────────────────────────────────────────
  {
    id: 'bld-1-1',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Variables',
    unitIndex: 0,
    title: 'Store information in a variable',
    emoji: '📦',
    realWorldUse: 'Used in: every program — variables store names, scores, settings',
    concept: `A **variable** is like a labelled box that stores a value. You name it, then put something in it using \`=\`.\n\n\`\`\`python\nname = "Max"\nage = 10\nprint(name)\nprint(age)\n\`\`\`\n\nYou can use the variable later just by writing its name — no speech marks needed!`,
    example: `animal = "elephant"\nweight = 6000\nprint(animal)\nprint(weight)`,
    challenge: `Create two variables:\n- \`city\` set to your favourite city\n- \`population\` set to any number\n\nThen print both variables.`,
    starterCode: `city = "___"\npopulation = ___\nprint(city)\nprint(population)`,
    solutionCode: `city = "London"\npopulation = 9000000\nprint(city)\nprint(population)`,
    checkOutput: (o) => o.trim().split('\n').length >= 2,
    expectedHint: 'Two lines of output — the city name and a number',
    hints: [
      'Replace the first ___ with a city name in speech marks',
      'Replace the second ___ with a number (no speech marks for numbers)',
      'Make sure you have both print() lines',
    ],
  },
  {
    id: 'bld-2-1',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'If / Else',
    unitIndex: 0,
    title: 'Make decisions with if',
    emoji: '🤔',
    realWorldUse: 'Used in: password checks, game win/lose logic, age verification',
    concept: `Programs can make decisions using **if / else**:\n\n\`\`\`python\ntemperature = 35\nif temperature > 30:\n    print("It's hot!")\nelse:\n    print("It's cool.")\n\`\`\`\n\nIf the condition is true, the indented code runs. Otherwise the \`else\` block runs.\n\n⚠️ The indentation (spaces) matters in Python!`,
    example: `score = 85\nif score >= 50:\n    print("You passed!")\nelse:\n    print("Try again!")`,
    challenge: `Write a program that checks if a number is **even or odd**:\n- Set \`number\` to 7\n- If \`number % 2 == 0\`, print \`"Even"\`\n- Otherwise print \`"Odd"\`\n\n*(The % symbol gives the remainder after dividing)*`,
    starterCode: `number = 7\nif number % 2 == ___:\n    print("Even")\nelse:\n    print("Odd")`,
    solutionCode: `number = 7\nif number % 2 == 0:\n    print("Even")\nelse:\n    print("Odd")`,
    checkOutput: (o) => o.trim() === 'Odd',
    expectedHint: 'Odd',
    hints: [
      'The remainder when 7 is divided by 2 is 1, not 0 — so it\'s odd',
      'Replace ___ with 0 (we check if remainder equals zero for even numbers)',
      '7 % 2 equals 1, which is not 0, so the else runs',
    ],
  },
  {
    id: 'bld-3-1',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Loops',
    unitIndex: 0,
    title: 'Loop through a list',
    emoji: '🔄',
    realWorldUse: 'Used in: displaying search results, processing student grades, rendering menus',
    concept: `A **list** stores multiple values:\n\n\`\`\`python\nanimals = ["cat", "dog", "elephant"]\n\`\`\`\n\nYou can loop through every item with **for...in**:\n\n\`\`\`python\nfor animal in animals:\n    print(animal)\n\`\`\`\n\nThis prints each animal one at a time!`,
    example: `colours = ["red", "green", "blue"]\nfor colour in colours:\n    print("I see", colour)`,
    challenge: `Create a list called \`planets\` with at least 3 planets.\nLoop through it and print each one with: \`"Planet:", planet\``,
    starterCode: `planets = ["Mercury", "Venus", "___"]\nfor planet in planets:\n    print("Planet:", ___)`,
    solutionCode: `planets = ["Mercury", "Venus", "Earth"]\nfor planet in planets:\n    print("Planet:", planet)`,
    checkOutput: (o) => o.includes('Planet:') && o.trim().split('\n').length >= 3,
    expectedHint: 'Planet: Mercury\nPlanet: Venus\nPlanet: ...',
    hints: [
      'Add a third planet name in speech marks where ___ is',
      'In the print line, replace ___ with the loop variable: planet',
    ],
  },
  {
    id: 'bld-4-1',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Functions',
    unitIndex: 0,
    title: 'Build your own function',
    emoji: '⚙️',
    realWorldUse: 'Used in: reusable game logic, calculator apps, data processing',
    concept: `A **function** is a named block of code you can run whenever you need it.\n\n\`\`\`python\ndef greet(name):\n    print("Hello,", name)\n\ngreet("Alice")\ngreet("Bob")\n\`\`\`\n\n\`def\` defines the function. The **parameter** (name) is the input. You **call** it by writing its name with brackets.`,
    example: `def double(number):\n    print(number * 2)\n\ndouble(5)\ndouble(10)`,
    challenge: `Write a function called \`square\` that takes a number and prints it multiplied by itself.\n\nThen call it with **4** and **9**.`,
    starterCode: `def square(number):\n    print(number ___ number)\n\nsquare(4)\nsquare(9)`,
    solutionCode: `def square(number):\n    print(number * number)\n\nsquare(4)\nsquare(9)`,
    checkOutput: (o) => o.includes('16') && o.includes('81'),
    expectedHint: '16\n81',
    hints: [
      'Replace ___ with the multiplication operator: *',
      '4 * 4 = 16, 9 * 9 = 81',
    ],
  },
  {
    id: 'bld-5-1',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Debugging',
    unitIndex: 0,
    title: 'Find the bug!',
    emoji: '🐛',
    realWorldUse: 'Used in: every professional programmer\'s daily job',
    concept: `**Debugging** means finding and fixing mistakes in your code. Bugs are normal — even expert programmers fix bugs every day!\n\nCommon bugs:\n- Missing speech marks around a string\n- Wrong indentation (spaces)\n- Misspelled variable name\n- Wrong operator (= vs ==)\n\nRead the error message — it often tells you the line number!`,
    example: `# This code has a bug — can you spot it?\n# name = Max   ← missing speech marks!\nname = "Max"  # ← fixed!\nprint(name)`,
    challenge: `This code has **2 bugs**. Fix them both so it prints:\n\`Hello, Ada!\nShe was born in 1815.\``,
    starterCode: `name = Ada\nyear = "1815"\nprint("Hello,", name + "!")\nprint("She was born in", year + ".")`,
    solutionCode: `name = "Ada"\nyear = 1815\nprint("Hello,", name + "!")\nprint("She was born in", str(year) + ".")`,
    checkOutput: (o) => o.includes('Ada') && o.includes('1815'),
    expectedHint: 'Hello, Ada!\nShe was born in 1815.',
    hints: [
      'Bug 1: "Ada" needs speech marks — it\'s a string, not a number',
      'Bug 2: 1815 is a number, not a string — remove the speech marks',
      'You may need str(year) to combine a number with text',
    ],
  },

  // ── MATH ─────────────────────────────────────────────────────────────────────
  {
    id: 'bld-m-1-1',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Arithmetic',
    unitIndex: 0,
    title: 'Do maths with variables',
    emoji: '🧮',
    realWorldUse: 'Used in: budget calculators, physics engines, score systems',
    concept: `Variables can hold numbers — and you can do maths with them!\n\n\`\`\`python\nlength = 8\nwidth = 5\narea = length * width\nprint("Area:", area)\n\`\`\`\n\nThe \`*\` symbol means multiply. \`+\` adds, \`-\` subtracts, \`/\` divides.`,
    example: `speed = 60\ntime = 3\ndistance = speed * time\nprint("Distance:", distance)`,
    challenge: `Calculate the **area of a rectangle**:\n- Set \`length\` to 12\n- Set \`width\` to 7\n- Calculate \`area = length * width\`\n- Print: \`"Area:", area\``,
    starterCode: `length = ___\nwidth = ___\narea = length * width\nprint("Area:", area)`,
    solutionCode: `length = 12\nwidth = 7\narea = length * width\nprint("Area:", area)`,
    checkOutput: (o) => o.includes('84'),
    expectedHint: 'Area: 84',
    hints: [
      'Set length to 12 and width to 7',
      '12 × 7 = 84',
      'The print line is already done for you',
    ],
  },
  {
    id: 'bld-m-1-2',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Arithmetic',
    unitIndex: 1,
    title: 'The power of exponents',
    emoji: '💥',
    realWorldUse: 'Used in: compound interest, graphics scaling, password strength',
    concept: `An **exponent** means multiplying a number by itself multiple times.\n\n2³ = 2 × 2 × 2 = 8\n\nIn Python, you use \`**\` for exponents:\n\n\`\`\`python\nprint(2 ** 3)   # prints 8\nprint(5 ** 2)   # prints 25 (5 squared)\n\`\`\``,
    example: `print("2 squared:", 2 ** 2)\nprint("2 cubed:", 2 ** 3)\nprint("10 squared:", 10 ** 2)`,
    challenge: `Print:\n1. 3 to the power of 4 (3⁴)\n2. 7 squared (7²)\n3. 2 to the power of 8 (2⁸)`,
    starterCode: `print("3^4 =", 3 ** ___)\nprint("7^2 =", 7 ** ___)\nprint("2^8 =", 2 ** ___)`,
    solutionCode: `print("3^4 =", 3 ** 4)\nprint("7^2 =", 7 ** 2)\nprint("2^8 =", 2 ** 8)`,
    checkOutput: (o) => o.includes('81') && o.includes('49') && o.includes('256'),
    expectedHint: '3^4 = 81\n7^2 = 49\n2^8 = 256',
    hints: [
      '3^4 means 3 multiplied by itself 4 times: 3×3×3×3 = 81',
      '7² means 7×7 = 49',
      '2⁸ means 2 multiplied 8 times = 256 (computers love powers of 2!)',
    ],
  },
  {
    id: 'bld-m-2-1',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Geometry',
    unitIndex: 0,
    title: 'Area and perimeter',
    emoji: '📐',
    realWorldUse: 'Used in: architecture software, game map design, flooring calculators',
    concept: `Two key measurements for rectangles:\n\n**Perimeter** = distance around the outside = 2 × (length + width)\n\n**Area** = space inside = length × width\n\nIn Python:\n\`\`\`python\nlength = 10\nwidth = 4\nperimeter = 2 * (length + width)\narea = length * width\n\`\`\``,
    example: `length = 8\nwidth = 3\nperimeter = 2 * (length + width)\narea = length * width\nprint("Perimeter:", perimeter)\nprint("Area:", area)`,
    challenge: `A swimming pool is **25m long** and **10m wide**.\nCalculate and print both its perimeter and area.`,
    starterCode: `length = ___\nwidth = ___\nperimeter = 2 * (length + width)\narea = length * ___\nprint("Perimeter:", perimeter, "m")\nprint("Area:", area, "m²")`,
    solutionCode: `length = 25\nwidth = 10\nperimeter = 2 * (length + width)\narea = length * width\nprint("Perimeter:", perimeter, "m")\nprint("Area:", area, "m²")`,
    checkOutput: (o) => o.includes('70') && o.includes('250'),
    expectedHint: 'Perimeter: 70 m\nArea: 250 m²',
    hints: [
      'Set length to 25 and width to 10',
      'Perimeter = 2 × (25 + 10) = 2 × 35 = 70',
      'Area = 25 × 10 = 250',
    ],
  },
  {
    id: 'bld-m-3-1',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Algebra',
    unitIndex: 0,
    title: 'Solve for x with code',
    emoji: '🔡',
    realWorldUse: 'Used in: physics simulations, financial modelling, robotics',
    concept: `**Algebra** uses letters (like x) to represent unknown numbers. In Python, those letters are just variables!\n\nIf we know that: **distance = speed × time**\n\nAnd we know distance = 150 and time = 3, we can find speed:\n\n\`\`\`python\ndistance = 150\ntime = 3\nspeed = distance / time  # solve for speed\nprint("Speed:", speed)\n\`\`\``,
    example: `# Formula: profit = revenue - cost\nrevenue = 500\ncost = 320\nprofit = revenue - cost\nprint("Profit:", profit)`,
    challenge: `Use the formula **temperature_f = (temperature_c × 9/5) + 32** to convert:\n- 0°C to Fahrenheit\n- 100°C to Fahrenheit\n- 37°C to Fahrenheit (body temperature!)`,
    starterCode: `def to_fahrenheit(c):\n    return (c * ___/5) + ___\n\nprint("0°C =", to_fahrenheit(0), "°F")\nprint("100°C =", to_fahrenheit(___), "°F")\nprint("37°C =", to_fahrenheit(___), "°F")`,
    solutionCode: `def to_fahrenheit(c):\n    return (c * 9/5) + 32\n\nprint("0°C =", to_fahrenheit(0), "°F")\nprint("100°C =", to_fahrenheit(100), "°F")\nprint("37°C =", to_fahrenheit(37), "°F")`,
    checkOutput: (o) => o.includes('32') && o.includes('212') && o.includes('98'),
    expectedHint: '0°C = 32.0 °F\n100°C = 212.0 °F\n37°C = 98.6 °F',
    hints: [
      'The formula multiplies by 9/5 and adds 32',
      '0°C = 32°F (freezing point of water)',
      '100°C = 212°F (boiling point), 37°C ≈ 98.6°F (body temperature)',
    ],
  },
  {
    id: 'bld-1-2',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Variables',
    unitIndex: 1,
    title: 'Update a variable',
    emoji: '🔄',
    realWorldUse: 'Used in: score counters, health bars, bank balances',
    concept: `Variables can **change**! You can update them with a new value.\n\n\`\`\`python\nscore = 0\nscore = score + 10\nprint(score)  # prints 10\n\`\`\`\n\nThis is how game scores work — they start at 0 and grow!`,
    example: `money = 50\nmoney = money + 25\nprint("I have", money, "coins")`,
    challenge: `Start with \`score = 0\`. Add 10, then add 20 more, then print the final score.`,
    starterCode: `score = ___\nscore = score + ___\nscore = score + ___\nprint("Score:", score)`,
    solutionCode: `score = 0\nscore = score + 10\nscore = score + 20\nprint("Score:", score)`,
    checkOutput: (o) => o.includes('30'),
    expectedHint: 'Score: 30',
    hints: [
      'Start with score = 0',
      'Add 10 first, then add 20',
      '0 + 10 + 20 = 30',
    ],
  },
  {
    id: 'bld-2-2',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'If / Else',
    unitIndex: 1,
    title: 'Compare with elif',
    emoji: '📊',
    realWorldUse: 'Used in: grade calculators, weather alerts, age categories',
    concept: `You can check **multiple conditions** with \`elif\` (else-if):\n\n\`\`\`python\nage = 15\nif age >= 18:\n    print("Adult")\nelif age >= 13:\n    print("Teenager")\nelse:\n    print("Child")\n\`\`\`\n\nPython checks each one from top to bottom and runs the first match.`,
    example: `score = 75\nif score >= 90:\n    print("A grade")\nelif score >= 70:\n    print("B grade")\nelse:\n    print("Keep trying!")`,
    challenge: `Write a program that checks a test \`score\`:\n- 90 or above: print "Excellent"\n- 70 or above: print "Good"\n- 50 or above: print "Pass"\n- Below 50: print "Fail"\n\nSet score to 82 and test it.`,
    starterCode: `score = 82\nif score >= 90:\n    print("___")\nelif score >= 70:\n    print("___")\nelif score >= 50:\n    print("___")\nelse:\n    print("___")`,
    solutionCode: `score = 82\nif score >= 90:\n    print("Excellent")\nelif score >= 70:\n    print("Good")\nelif score >= 50:\n    print("Pass")\nelse:\n    print("Fail")`,
    checkOutput: (o) => o.trim() === 'Good',
    expectedHint: 'Good',
    hints: [
      '82 is >= 70 but not >= 90, so the elif runs',
      'Fill in: Excellent, Good, Pass, Fail',
    ],
  },
  {
    id: 'bld-3-2',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Loops',
    unitIndex: 1,
    title: 'Count with range',
    emoji: '🔢',
    realWorldUse: 'Used in: timers, pagination, batch processing',
    concept: `\`range(start, stop)\` counts from start up to (not including) stop:\n\n\`\`\`python\nfor i in range(1, 6):\n    print(i)\n\`\`\`\n\nThis prints 1, 2, 3, 4, 5 — NOT 6!`,
    example: `for i in range(5, 10):\n    print(i)`,
    challenge: `Print all numbers from **10 to 20** (including 20).`,
    starterCode: `for i in range(___, ___):\n    print(i)`,
    solutionCode: `for i in range(10, 21):\n    print(i)`,
    checkOutput: (o) => o.includes('10') && o.includes('20'),
    expectedHint: '10 through 20, each on its own line',
    hints: [
      'Start at 10',
      'Stop at 21 (range stops BEFORE the second number)',
    ],
  },
  {
    id: 'bld-4-2',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Functions',
    unitIndex: 1,
    title: 'Function with two inputs',
    emoji: '🔗',
    realWorldUse: 'Used in: calculator apps, physics formulas, currency converters',
    concept: `Functions can take **multiple parameters**:\n\n\`\`\`python\ndef add(a, b):\n    print(a + b)\n\nadd(3, 7)  # prints 10\n\`\`\``,
    example: `def greet(name, age):\n    print("Hi", name, "— you are", age)\n\ngreet("Max", 10)`,
    challenge: `Write a function \`multiply(a, b)\` that prints a × b.\nCall it with (6, 7) and (9, 4).`,
    starterCode: `def multiply(a, b):\n    print(a ___ b)\n\nmultiply(6, ___)\nmultiply(___, 4)`,
    solutionCode: `def multiply(a, b):\n    print(a * b)\n\nmultiply(6, 7)\nmultiply(9, 4)`,
    checkOutput: (o) => o.includes('42') && o.includes('36'),
    expectedHint: '42\n36',
    hints: [
      'Use * for multiplication',
      '6 × 7 = 42, 9 × 4 = 36',
    ],
  },
  {
    id: 'bld-6-1',
    tier: 'BUILDER',
    subject: 'coding',
    unit: 'Strings',
    unitIndex: 0,
    title: 'Join strings together',
    emoji: '🔗',
    realWorldUse: 'Used in: building URLs, creating messages, formatting names',
    concept: `You can **join** strings using **+**:\n\n\`\`\`python\nfirst = "Hello"\nsecond = "World"\nprint(first + " " + second)\n\`\`\`\n\nThis prints "Hello World".`,
    example: `name = "Ada"\nprint("Hello, " + name + "!")`,
    challenge: `Create variables \`first_name\` and \`last_name\`. Join them with a space and print the full name.`,
    starterCode: `first_name = "___"\nlast_name = "___"\nprint(first_name + "___" + last_name)`,
    solutionCode: `first_name = "Ada"\nlast_name = "Lovelace"\nprint(first_name + " " + last_name)`,
    checkOutput: (o) => o.trim().split(' ').length >= 2,
    expectedHint: 'First Last (full name with a space)',
    hints: [
      'Put a space " " between the names',
      'Use + to join: first_name + " " + last_name',
    ],
  },
  {
    id: 'bld-m-4-1',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Arithmetic',
    unitIndex: 2,
    title: 'Order of operations',
    emoji: '🧠',
    realWorldUse: 'Used in: calculators, spreadsheets, financial software',
    concept: `Python follows **BODMAS** — Brackets, Orders, Division, Multiplication, Addition, Subtraction.\n\n\`\`\`python\nprint(2 + 3 * 4)    # 14, not 20!\nprint((2 + 3) * 4)  # 20 — brackets first!\n\`\`\``,
    example: `print(10 + 2 * 3)     # 16\nprint((10 + 2) * 3)  # 36`,
    challenge: `Print the result of:\n1. 3 + 4 * 5 (no brackets)\n2. (3 + 4) * 5 (with brackets)\n3. 100 / (2 + 3) (brackets in division)`,
    starterCode: `print(3 + 4 * 5)\nprint((3 + 4) * 5)\nprint(100 / (___ + ___))`,
    solutionCode: `print(3 + 4 * 5)\nprint((3 + 4) * 5)\nprint(100 / (2 + 3))`,
    checkOutput: (o) => o.includes('23') && o.includes('35') && o.includes('20'),
    expectedHint: '23\n35\n20.0',
    hints: [
      '3 + 4 * 5 = 3 + 20 = 23 (multiply first)',
      '(3 + 4) * 5 = 7 * 5 = 35 (brackets first)',
      '100 / (2 + 3) = 100 / 5 = 20',
    ],
  },
  {
    id: 'bld-m-5-1',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Algebra',
    unitIndex: 1,
    title: 'Solve equations with code',
    emoji: '⚖️',
    realWorldUse: 'Used in: physics engines, budget planning, engineering software',
    concept: `You can use code to solve equations!\n\nIf **2x + 3 = 15**, then **x = (15 - 3) / 2**:\n\n\`\`\`python\nresult = 15\nx = (result - 3) / 2\nprint("x =", x)\n\`\`\``,
    example: `# Solve: 3x - 6 = 12\n# x = (12 + 6) / 3\nx = (12 + 6) / 3\nprint("x =", x)  # 6.0`,
    challenge: `Solve: **5x + 10 = 45**\nRearrange: x = (45 - 10) / 5\nPrint the answer.`,
    starterCode: `x = (___ - ___) / ___\nprint("x =", x)`,
    solutionCode: `x = (45 - 10) / 5\nprint("x =", x)`,
    checkOutput: (o) => o.includes('7'),
    expectedHint: 'x = 7.0',
    hints: [
      'Subtract 10 from 45 first',
      'Then divide by 5',
      '(45 - 10) / 5 = 35 / 5 = 7',
    ],
  },
  {
    id: 'bld-m-6-1',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Geometry',
    unitIndex: 1,
    title: 'Circle area and circumference',
    emoji: '⭕',
    realWorldUse: 'Used in: wheel design, pizza calculators, satellite orbits',
    concept: `Two formulas for circles:\n\n**Area** = π × r²\n**Circumference** = 2 × π × r\n\nIn Python:\n\`\`\`python\npi = 3.14159\nradius = 5\narea = pi * radius * radius\ncircumference = 2 * pi * radius\n\`\`\``,
    example: `pi = 3.14159\nr = 7\narea = pi * r * r\nprint("Area:", round(area, 2))`,
    challenge: `Calculate for a circle with radius **10**:\n1. Area = π × r²\n2. Circumference = 2 × π × r\n\nUse pi = 3.14159`,
    starterCode: `pi = 3.14159\nr = ___\narea = pi * r * ___\ncircumference = 2 * pi * ___\nprint("Area:", round(area, 2))\nprint("Circumference:", round(circumference, 2))`,
    solutionCode: `pi = 3.14159\nr = 10\narea = pi * r * r\ncircumference = 2 * pi * r\nprint("Area:", round(area, 2))\nprint("Circumference:", round(circumference, 2))`,
    checkOutput: (o) => o.includes('314') && o.includes('62'),
    expectedHint: 'Area: 314.16\nCircumference: 62.83',
    hints: [
      'Set r to 10',
      'Area = pi * r * r',
      'Circumference = 2 * pi * r',
    ],
  },
  {
    id: 'bld-m-7-1',
    tier: 'BUILDER',
    subject: 'math',
    unit: 'Arithmetic',
    unitIndex: 3,
    title: 'Remainders and modulo',
    emoji: '🔢',
    realWorldUse: 'Used in: even/odd checks, clock arithmetic, hash functions',
    concept: `The **%** (modulo) operator gives the **remainder** after division:\n\n\`\`\`python\nprint(10 % 3)  # 1 (10 ÷ 3 = 3 remainder 1)\nprint(8 % 2)   # 0 (8 is even — no remainder)\n\`\`\`\n\nThis is super useful for checking if numbers divide evenly!`,
    example: `print(17 % 5)   # 2\nprint(20 % 4)   # 0\nprint(13 % 2)   # 1 (odd!)`,
    challenge: `Print the remainder of:\n1. 23 divided by 5\n2. 100 divided by 7\n3. 49 divided by 6`,
    starterCode: `print(23 % ___)\nprint(100 % ___)\nprint(49 % ___)`,
    solutionCode: `print(23 % 5)\nprint(100 % 7)\nprint(49 % 6)`,
    checkOutput: (o) => o.includes('3') && o.includes('2') && o.includes('1'),
    expectedHint: '3\n2\n1',
    hints: [
      '23 ÷ 5 = 4 remainder 3',
      '100 ÷ 7 = 14 remainder 2',
      '49 ÷ 6 = 8 remainder 1',
    ],
  },
]

// ── CREATOR (12–15): Real Python, algorithms, proofs ─────────────────────────

const CREATOR_LESSONS: Lesson[] = [
  // ── CODING ───────────────────────────────────────────────────────────────────
  {
    id: 'crt-1-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Data Structures',
    unitIndex: 0,
    title: 'Lists and indexing',
    emoji: '📋',
    realWorldUse: 'Used in: playlists, databases, search results, recommendation engines',
    concept: `**Lists** are ordered collections. Items are accessed by their **index** — starting at 0.\n\n\`\`\`python\nfruits = ["apple", "banana", "cherry"]\nprint(fruits[0])   # apple\nprint(fruits[2])   # cherry\nprint(len(fruits)) # 3\n\`\`\`\n\nYou can **append**, **remove**, and **slice** lists:\n\`\`\`python\nfruits.append("mango")\nfruits.remove("banana")\nprint(fruits[1:3])  # slice: index 1 up to (not including) 3\n\`\`\``,
    example: `scores = [95, 72, 88, 61, 79]\nprint("First:", scores[0])\nprint("Last:", scores[-1])\nprint("Top 3:", scores[:3])`,
    challenge: `Given this list of temperatures:\n\`temps = [22, 35, 18, 41, 27, 15, 33]\`\n\nPrint:\n1. The hottest temperature (index 3)\n2. The number of readings (use len())\n3. The first 3 readings (use a slice)`,
    starterCode: `temps = [22, 35, 18, 41, 27, 15, 33]\n\nprint("Hottest:", temps[___])\nprint("Total readings:", ___(temps))\nprint("First 3:", temps[___:___])`,
    solutionCode: `temps = [22, 35, 18, 41, 27, 15, 33]\n\nprint("Hottest:", temps[3])\nprint("Total readings:", len(temps))\nprint("First 3:", temps[0:3])`,
    checkOutput: (o) => o.includes('41') && o.includes('7') && o.includes('22'),
    expectedHint: 'Hottest: 41\nTotal readings: 7\nFirst 3: [22, 35, 18]',
    hints: [
      'The hottest is at index 3 (remember: counting starts at 0)',
      'len() counts how many items are in a list',
      'A slice from 0 to 3 gives the first 3 items: [0:3]',
    ],
  },
  {
    id: 'crt-2-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Dictionaries',
    unitIndex: 0,
    title: 'Key-value pairs',
    emoji: '🗂️',
    realWorldUse: 'Used in: JSON APIs, user profiles, game inventories, config files',
    concept: `A **dictionary** stores data as key-value pairs — like a real dictionary where you look up a word to get its meaning.\n\n\`\`\`python\nperson = {\n    "name": "Ada Lovelace",\n    "born": 1815,\n    "field": "Mathematics"\n}\nprint(person["name"])\nprint(person["born"])\n\`\`\`\n\nAccess values with \`dict["key"]\`. Add or update: \`dict["key"] = value\`.`,
    example: `planet = {"name": "Mars", "moons": 2, "distance_km": 225000000}\nprint(planet["name"], "has", planet["moons"], "moons")\nplanet["explored"] = True\nprint("Explored:", planet["explored"])`,
    challenge: `Create a dictionary called \`book\` with keys:\n- \`"title"\` — any book title\n- \`"author"\` — the author's name  \n- \`"year"\` — year published\n- \`"pages"\` — number of pages\n\nThen print a summary: \`"Title by Author (year) — pages pages"\``,
    starterCode: `book = {\n    "title": "___",\n    "author": "___",\n    "year": ___,\n    "pages": ___\n}\n\nprint(book["title"], "by", book["___"], "("+str(book["year"])+")", "—", book["pages"], "pages")`,
    solutionCode: `book = {\n    "title": "Harry Potter",\n    "author": "J.K. Rowling",\n    "year": 1997,\n    "pages": 223\n}\n\nprint(book["title"], "by", book["author"], "("+str(book["year"])+")", "—", book["pages"], "pages")`,
    checkOutput: (o) => o.includes('by') && o.includes('—'),
    expectedHint: '[Title] by [Author] (year) — pages pages',
    hints: [
      'Fill in the four string/number values in the dictionary',
      'In the print line, replace ___ with "author"',
      'str() converts the year number to a string so it can join with text',
    ],
  },
  {
    id: 'crt-3-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Functions',
    unitIndex: 0,
    title: 'Functions with return values',
    emoji: '↩️',
    realWorldUse: 'Used in: health apps, physics engines, financial calculations',
    concept: `Functions can **return** a value instead of just printing it. This lets you use the result elsewhere.\n\n\`\`\`python\ndef celsius_to_fahrenheit(c):\n    return (c * 9/5) + 32\n\ntemp = celsius_to_fahrenheit(100)\nprint(temp)  # 212.0\n\`\`\`\n\nUsing \`return\` makes functions reusable and composable — the output can feed into other calculations.`,
    example: `def area_of_circle(radius):\n    pi = 3.14159\n    return pi * radius * radius\n\nsmall = area_of_circle(5)\nlarge = area_of_circle(10)\nprint("Small circle area:", round(small, 2))\nprint("Large circle area:", round(large, 2))`,
    challenge: `Write a function \`bmi(weight_kg, height_m)\` that calculates Body Mass Index:\n\n**BMI = weight / (height × height)**\n\nReturn the result rounded to 1 decimal place using \`round(value, 1)\`.\n\nThen call it with weight=70, height=1.75 and print the result.`,
    starterCode: `def bmi(weight_kg, height_m):\n    result = weight_kg ___ (height_m ___ height_m)\n    return round(result, 1)\n\nmy_bmi = bmi(___, ___)\nprint("BMI:", my_bmi)`,
    solutionCode: `def bmi(weight_kg, height_m):\n    result = weight_kg / (height_m * height_m)\n    return round(result, 1)\n\nmy_bmi = bmi(70, 1.75)\nprint("BMI:", my_bmi)`,
    checkOutput: (o) => o.includes('22.9') || o.includes('22.857'),
    expectedHint: 'BMI: 22.9',
    hints: [
      'BMI divides weight by height squared: weight / (height * height)',
      'Use / for division and * for multiplication',
      'Call bmi(70, 1.75) — the result should be 22.9',
    ],
  },
  {
    id: 'crt-4-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Loops & Logic',
    unitIndex: 0,
    title: 'FizzBuzz — the classic challenge',
    emoji: '🎯',
    realWorldUse: 'Used in: programming interviews at Google, Amazon, Meta, and every tech company',
    concept: `**FizzBuzz** is a famous programming interview problem. Here's the challenge:\n\nFor numbers 1 to 20:\n- If divisible by 3, print \`"Fizz"\`\n- If divisible by 5, print \`"Buzz"\`  \n- If divisible by both 3 and 5, print \`"FizzBuzz"\`\n- Otherwise, print the number\n\nKey tools: \`range()\`, \`if/elif/else\`, \`%\` (modulo operator)`,
    example: `for i in range(1, 6):\n    if i % 2 == 0:\n        print("Even")\n    else:\n        print(i)`,
    challenge: `Implement FizzBuzz for numbers **1 to 20**.\n\nRemember: check for FizzBuzz (both) **first**, then Fizz, then Buzz, then the number.`,
    starterCode: `for i in range(1, 21):\n    if i % 3 == 0 and i % 5 == ___:\n        print("FizzBuzz")\n    elif i % ___ == 0:\n        print("Fizz")\n    elif i % 5 == ___:\n        print("Buzz")\n    else:\n        print(___)`,
    solutionCode: `for i in range(1, 21):\n    if i % 3 == 0 and i % 5 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)`,
    checkOutput: (o) => o.includes('FizzBuzz') && o.includes('Fizz') && o.includes('Buzz') && o.includes('1\n'),
    expectedHint: '1, 2, Fizz, 4, Buzz, Fizz, 7, 8, Fizz, Buzz, 11, Fizz, 13, 14, FizzBuzz...',
    hints: [
      'The first blank in the FizzBuzz check should be 0 (divisible by 5)',
      'The second blank (elif) should be 3 — checking divisible by 3',
      'The third blank should be 0 — checking divisible by 5',
      'The final blank should be i — print the number itself',
    ],
  },
  {
    id: 'crt-5-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Algorithms',
    unitIndex: 0,
    title: 'Linear search',
    emoji: '🔍',
    realWorldUse: 'Used in: database lookups, contact search, content filtering',
    concept: `A **search algorithm** finds something in a list. The simplest is **linear search** — checking each item one by one until you find a match.\n\n\`\`\`python\ndef linear_search(items, target):\n    for i in range(len(items)):\n        if items[i] == target:\n            return i  # found at index i\n    return -1  # not found\n\`\`\`\n\nIt returns the **index** where the item was found, or -1 if not found.`,
    example: `names = ["Alice", "Bob", "Charlie", "Diana"]\nfor i in range(len(names)):\n    if names[i] == "Charlie":\n        print("Found at index", i)`,
    challenge: `Write a \`linear_search(items, target)\` function.\nTest it with this list of primes: \`[2, 3, 5, 7, 11, 13, 17, 19]\`\n- Search for **13** (should return index 5)\n- Search for **10** (should return -1, not found)`,
    starterCode: `def linear_search(items, target):\n    for i in range(___(items)):\n        if items[___] == target:\n            return ___\n    return -1\n\nprimes = [2, 3, 5, 7, 11, 13, 17, 19]\nprint("13 at index:", linear_search(primes, 13))\nprint("10 at index:", linear_search(primes, 10))`,
    solutionCode: `def linear_search(items, target):\n    for i in range(len(items)):\n        if items[i] == target:\n            return i\n    return -1\n\nprimes = [2, 3, 5, 7, 11, 13, 17, 19]\nprint("13 at index:", linear_search(primes, 13))\nprint("10 at index:", linear_search(primes, 10))`,
    checkOutput: (o) => o.includes('5') && o.includes('-1'),
    expectedHint: '13 at index: 5\n10 at index: -1',
    hints: [
      'Use len(items) to get the list length for range()',
      'Use items[i] to access the current element',
      'Return i when found, return -1 at the end if nothing matched',
    ],
  },

  // ── MATH ─────────────────────────────────────────────────────────────────────
  {
    id: 'crt-m-1-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Statistics',
    unitIndex: 0,
    title: 'Mean, median and mode',
    emoji: '📊',
    realWorldUse: 'Used in: data science, polling, sports analytics, medical research',
    concept: `Three ways to describe the "centre" of a dataset:\n\n- **Mean** (average) = sum of values ÷ count\n- **Median** = middle value when sorted\n- **Mode** = most common value\n\n\`\`\`python\nscores = [4, 7, 2, 9, 4, 6, 4]\nmean = sum(scores) / len(scores)\nprint("Mean:", mean)\n\`\`\``,
    example: `data = [10, 20, 30, 20, 40]\nmean = sum(data) / len(data)\nprint("Mean:", mean)\nsorted_data = sorted(data)\nprint("Median:", sorted_data[len(sorted_data)//2])`,
    challenge: `Given test scores: \`[72, 85, 91, 68, 85, 77, 91, 85, 63, 90]\`\n\n1. Print the **mean** (rounded to 1 decimal place)\n2. Print the **median** (sort first, pick middle)\n3. Print the **highest** and **lowest** score`,
    starterCode: `scores = [72, 85, 91, 68, 85, 77, 91, 85, 63, 90]\n\nmean = round(sum(scores) / ___(scores), 1)\n\nsorted_scores = sorted(scores)\nmedian = sorted_scores[___ // 2]\n\nprint("Mean:", ___)\nprint("Median:", ___)\nprint("Highest:", max(scores))\nprint("Lowest:", min(scores))`,
    solutionCode: `scores = [72, 85, 91, 68, 85, 77, 91, 85, 63, 90]\n\nmean = round(sum(scores) / len(scores), 1)\n\nsorted_scores = sorted(scores)\nmedian = sorted_scores[len(sorted_scores) // 2]\n\nprint("Mean:", mean)\nprint("Median:", median)\nprint("Highest:", max(scores))\nprint("Lowest:", min(scores))`,
    checkOutput: (o) => o.includes('80') && o.includes('85'),
    expectedHint: 'Mean: 80.7\nMedian: 85\nHighest: 91\nLowest: 63',
    hints: [
      'Use len(scores) to get the count for the mean',
      'Sort first, then pick the middle index: len // 2',
      'Python has built-in max() and min() functions',
    ],
  },
  {
    id: 'crt-m-2-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Number Theory',
    unitIndex: 0,
    title: 'Prime number checker',
    emoji: '🔢',
    realWorldUse: 'Used in: encryption (RSA), cryptography, secure banking',
    concept: `A **prime number** is only divisible by 1 and itself. Examples: 2, 3, 5, 7, 11, 13...\n\nTo check if a number is prime:\n- Try dividing it by every number from 2 up to its square root\n- If any division has zero remainder, it's NOT prime\n\nWhy square root? Because factors come in pairs — if one factor is bigger than √n, the other must be smaller.`,
    example: `def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, n):\n        if n % i == 0:\n            return False\n    return True\n\nprint(is_prime(7))   # True\nprint(is_prime(10))  # False`,
    challenge: `Write \`is_prime(n)\` and use it to print all prime numbers from **1 to 50**.`,
    starterCode: `def is_prime(n):\n    if n < ___:\n        return False\n    for i in range(2, n):\n        if n % i == ___:\n            return False\n    return True\n\nprimes = []\nfor num in range(1, 51):\n    if is_prime(___):\n        primes.append(num)\n\nprint("Primes 1-50:", primes)`,
    solutionCode: `def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, n):\n        if n % i == 0:\n            return False\n    return True\n\nprimes = []\nfor num in range(1, 51):\n    if is_prime(num):\n        primes.append(num)\n\nprint("Primes 1-50:", primes)`,
    checkOutput: (o) => o.includes('2') && o.includes('47') && o.includes('43'),
    expectedHint: 'Primes 1-50: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]',
    hints: [
      'A prime must be >= 2, so return False if n < 2',
      'If n % i == 0, it\'s divisible — not prime, return False',
      'If no divisor found in the loop, return True',
    ],
  },
  {
    id: 'crt-m-3-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Geometry',
    unitIndex: 0,
    title: 'Pythagoras theorem in code',
    emoji: '📐',
    realWorldUse: 'Used in: GPS distance, game collision detection, architecture software',
    concept: `**Pythagoras' theorem**: In a right-angled triangle,\n\n**a² + b² = c²**\n\nWhere c is the hypotenuse (longest side). To find c:\n\nc = √(a² + b²)\n\nIn Python:\n\`\`\`python\nimport math\nc = math.sqrt(a**2 + b**2)\n\`\`\``,
    example: `import math\n\na = 3\nb = 4\nc = math.sqrt(a**2 + b**2)\nprint("Hypotenuse:", c)  # 5.0 — the famous 3-4-5 triangle!`,
    challenge: `Write a function \`hypotenuse(a, b)\` that returns the hypotenuse.\n\nTest it with:\n1. a=3, b=4 (answer: 5.0)\n2. a=5, b=12 (answer: 13.0)\n3. a=8, b=15 (answer: 17.0)`,
    starterCode: `import math\n\ndef hypotenuse(a, b):\n    return math.sqrt(a___ + b___)\n\nprint("3,4 →", hypotenuse(3, ___))\nprint("5,12 →", hypotenuse(5, ___))\nprint("8,15 →", hypotenuse(___, 15))`,
    solutionCode: `import math\n\ndef hypotenuse(a, b):\n    return math.sqrt(a**2 + b**2)\n\nprint("3,4 →", hypotenuse(3, 4))\nprint("5,12 →", hypotenuse(5, 12))\nprint("8,15 →", hypotenuse(8, 15))`,
    checkOutput: (o) => o.includes('5.0') && o.includes('13.0') && o.includes('17.0'),
    expectedHint: '3,4 → 5.0\n5,12 → 13.0\n8,15 → 17.0',
    hints: [
      'Use ** for exponents: a**2 means a squared',
      'math.sqrt() calculates the square root',
      '3,4,5 / 5,12,13 / 8,15,17 are all "Pythagorean triples"',
    ],
  },
  {
    id: 'crt-6-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Algorithms',
    unitIndex: 1,
    title: 'Bubble sort',
    emoji: '🫧',
    realWorldUse: 'Used in: teaching sorting fundamentals, small dataset sorting, interview prep',
    concept: `**Bubble sort** repeatedly steps through a list, compares adjacent items, and swaps them if they're in the wrong order.\n\n\`\`\`python\ndef bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(0, n - i - 1):\n            if arr[j] > arr[j + 1]:\n                arr[j], arr[j + 1] = arr[j + 1], arr[j]\n    return arr\n\`\`\`\n\nTime complexity: **O(n²)** — slow for big lists, but easy to understand!`,
    example: `def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(0, n - i - 1):\n            if arr[j] > arr[j + 1]:\n                arr[j], arr[j + 1] = arr[j + 1], arr[j]\n    return arr\n\nprint(bubble_sort([5, 2, 8, 1, 9]))`,
    challenge: `Implement \`bubble_sort\` and sort this list: \`[64, 34, 25, 12, 22, 11, 90]\`\nPrint the sorted result.`,
    starterCode: `def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(0, n - i - ___):\n            if arr[j] > arr[___]:\n                arr[j], arr[j + 1] = arr[___], arr[j]\n    return arr\n\nnums = [64, 34, 25, 12, 22, 11, 90]\nprint(bubble_sort(nums))`,
    solutionCode: `def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(0, n - i - 1):\n            if arr[j] > arr[j + 1]:\n                arr[j], arr[j + 1] = arr[j + 1], arr[j]\n    return arr\n\nnums = [64, 34, 25, 12, 22, 11, 90]\nprint(bubble_sort(nums))`,
    checkOutput: (o) => o.includes('11') && o.includes('90') && o.trim().startsWith('['),
    expectedHint: '[11, 12, 22, 25, 34, 64, 90]',
    hints: [
      'The inner range goes up to n - i - 1',
      'Compare arr[j] with arr[j + 1]',
      'Swap: arr[j], arr[j + 1] = arr[j + 1], arr[j]',
    ],
  },
  {
    id: 'crt-7-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Algorithms',
    unitIndex: 2,
    title: 'Binary search',
    emoji: '🎯',
    realWorldUse: 'Used in: database indexes, phone books, dictionary lookups, game dev',
    concept: `**Binary search** finds items in a SORTED list by repeatedly halving the search space.\n\n\`\`\`python\ndef binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n\`\`\`\n\nTime complexity: **O(log n)** — incredibly fast! A list of 1 million items takes at most 20 checks.`,
    example: `def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n\nnums = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]\nprint(binary_search(nums, 23))  # 5`,
    challenge: `Implement \`binary_search\` and find **38** in this sorted list:\n\`[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 38, 40]\`\n\nAlso search for **100** (not in list).`,
    starterCode: `def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= ___:\n        mid = (left + right) // ___\n        if arr[mid] == target:\n            return ___\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = ___ - 1\n    return -1\n\nnums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 38, 40]\nprint("38 at index:", binary_search(nums, 38))\nprint("100 at index:", binary_search(nums, 100))`,
    solutionCode: `def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n\nnums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 38, 40]\nprint("38 at index:", binary_search(nums, 38))\nprint("100 at index:", binary_search(nums, 100))`,
    checkOutput: (o) => o.includes('19') && o.includes('-1'),
    expectedHint: '38 at index: 19\n100 at index: -1',
    hints: [
      'while left <= right — keep searching while the range is valid',
      'mid = (left + right) // 2 — integer division',
      'Return mid when found, return -1 at the end',
      'When arr[mid] > target: right = mid - 1',
    ],
  },
  {
    id: 'crt-8-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Recursion',
    unitIndex: 0,
    title: 'Recursive factorial',
    emoji: '🔄',
    realWorldUse: 'Used in: tree traversal, file system navigation, divide-and-conquer algorithms',
    concept: `**Recursion** is when a function calls itself. Every recursive function needs:\n1. A **base case** (when to stop)\n2. A **recursive case** (how to break the problem down)\n\n\`\`\`python\ndef factorial(n):\n    if n == 0:\n        return 1  # base case\n    return n * factorial(n - 1)  # recursive case\n\`\`\`\n\n5! = 5 × 4 × 3 × 2 × 1 = 120`,
    example: `def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nprint(factorial(5))  # 120\nprint(factorial(10)) # 3628800`,
    challenge: `Write a recursive \`factorial(n)\` function.\nPrint factorial of 6, 8, and 10.`,
    starterCode: `def factorial(n):\n    if n <= ___:\n        return 1\n    return n * factorial(n - ___)\n\nprint("6! =", factorial(6))\nprint("8! =", factorial(___))\nprint("10! =", factorial(___))`,
    solutionCode: `def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nprint("6! =", factorial(6))\nprint("8! =", factorial(8))\nprint("10! =", factorial(10))`,
    checkOutput: (o) => o.includes('720') && o.includes('40320') && o.includes('3628800'),
    expectedHint: '6! = 720\n8! = 40320\n10! = 3628800',
    hints: [
      'Base case: n <= 1 returns 1',
      'Recursive case: n * factorial(n - 1)',
      '6! = 720, 8! = 40320, 10! = 3628800',
    ],
  },
  {
    id: 'crt-9-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Recursion',
    unitIndex: 1,
    title: 'Fibonacci sequence',
    emoji: '🐚',
    realWorldUse: 'Used in: financial modelling, nature patterns, algorithm analysis, art',
    concept: `The **Fibonacci sequence**: each number is the sum of the two before it.\n\n0, 1, 1, 2, 3, 5, 8, 13, 21, 34...\n\n\`\`\`python\ndef fibonacci(n):\n    if n <= 0:\n        return 0\n    if n == 1:\n        return 1\n    return fibonacci(n - 1) + fibonacci(n - 2)\n\`\`\`\n\nThis appears in nature: sunflower seeds, pinecones, nautilus shells!`,
    example: `def fibonacci(n):\n    if n <= 0: return 0\n    if n == 1: return 1\n    return fibonacci(n - 1) + fibonacci(n - 2)\n\nfor i in range(10):\n    print(fibonacci(i), end=" ")`,
    challenge: `Write a recursive \`fibonacci(n)\` function.\nPrint the first **12** Fibonacci numbers (indices 0 through 11).`,
    starterCode: `def fibonacci(n):\n    if n <= 0:\n        return ___\n    if n == 1:\n        return ___\n    return fibonacci(n - 1) + fibonacci(___)\n\nfor i in range(12):\n    print(fibonacci(i), end=" ")`,
    solutionCode: `def fibonacci(n):\n    if n <= 0:\n        return 0\n    if n == 1:\n        return 1\n    return fibonacci(n - 1) + fibonacci(n - 2)\n\nfor i in range(12):\n    print(fibonacci(i), end=" ")`,
    checkOutput: (o) => o.includes('0') && o.includes('1') && o.includes('89') && o.includes('144'),
    expectedHint: '0 1 1 2 3 5 8 13 21 34 55 89',
    hints: [
      'fibonacci(0) = 0, fibonacci(1) = 1',
      'fibonacci(n) = fibonacci(n-1) + fibonacci(n-2)',
      'The 12th number (index 11) is 89',
    ],
  },
  {
    id: 'crt-10-1',
    tier: 'CREATOR',
    subject: 'coding',
    unit: 'Error Handling',
    unitIndex: 0,
    title: 'Try except blocks',
    emoji: '🛡️',
    realWorldUse: 'Used in: web servers, file reading, API calls — every production system',
    concept: `**Error handling** lets your program survive mistakes instead of crashing.\n\n\`\`\`python\ntry:\n    number = int("hello")\nexcept ValueError:\n    print("That's not a number!")\n\`\`\`\n\nThe \`try\` block runs your code. If an error occurs, the \`except\` block catches it.`,
    example: `try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print("Cannot divide by zero!")\n\ntry:\n    num = int("42")\n    print("Got:", num)\nexcept ValueError:\n    print("Invalid number")`,
    challenge: `Write a function \`safe_divide(a, b)\` that:\n- Tries to return a / b\n- Catches ZeroDivisionError and returns "Error: cannot divide by zero"\n\nTest with: 10/3 and 10/0`,
    starterCode: `def safe_divide(a, b):\n    try:\n        return a ___ b\n    except ___:\n        return "Error: cannot divide by zero"\n\nprint(safe_divide(10, 3))\nprint(safe_divide(10, ___))`,
    solutionCode: `def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Error: cannot divide by zero"\n\nprint(safe_divide(10, 3))\nprint(safe_divide(10, 0))`,
    checkOutput: (o) => o.includes('3.') && o.includes('Error'),
    expectedHint: '3.333...\nError: cannot divide by zero',
    hints: [
      'Use / for division in the try block',
      'Catch ZeroDivisionError',
      'Test with b=0 to trigger the error',
    ],
  },
  {
    id: 'crt-m-4-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Algebra',
    unitIndex: 0,
    title: 'Quadratic formula in code',
    emoji: '📈',
    realWorldUse: 'Used in: physics engines, projectile motion, economics, engineering',
    concept: `The **quadratic formula** solves ax² + bx + c = 0:\n\n**x = (-b ± √(b² - 4ac)) / 2a**\n\nThe part under the square root (b² - 4ac) is called the **discriminant**:\n- Positive → two real solutions\n- Zero → one solution\n- Negative → no real solutions\n\n\`\`\`python\nimport math\ndef solve_quadratic(a, b, c):\n    disc = b**2 - 4*a*c\n    if disc < 0:\n        return "No real solutions"\n    x1 = (-b + math.sqrt(disc)) / (2*a)\n    x2 = (-b - math.sqrt(disc)) / (2*a)\n    return x1, x2\n\`\`\``,
    example: `import math\n\ndef solve_quadratic(a, b, c):\n    disc = b**2 - 4*a*c\n    if disc < 0:\n        return "No real solutions"\n    x1 = (-b + math.sqrt(disc)) / (2*a)\n    x2 = (-b - math.sqrt(disc)) / (2*a)\n    return x1, x2\n\nprint(solve_quadratic(1, -5, 6))  # (3.0, 2.0)`,
    challenge: `Use your \`solve_quadratic\` function to solve:\n1. x² - 5x + 6 = 0 (a=1, b=-5, c=6)\n2. x² + 2x - 8 = 0 (a=1, b=2, c=-8)\n3. x² + x + 1 = 0 (a=1, b=1, c=1 — no real solutions!)`,
    starterCode: `import math\n\ndef solve_quadratic(a, b, c):\n    disc = b**2 - 4*a*c\n    if disc < 0:\n        return "No real solutions"\n    x1 = (-b + math.sqrt(___)) / (2*a)\n    x2 = (-b - math.sqrt(disc)) / (___)\n    return x1, x2\n\nprint("x²-5x+6:", solve_quadratic(1, -5, 6))\nprint("x²+2x-8:", solve_quadratic(1, 2, ___))\nprint("x²+x+1:", solve_quadratic(1, 1, 1))`,
    solutionCode: `import math\n\ndef solve_quadratic(a, b, c):\n    disc = b**2 - 4*a*c\n    if disc < 0:\n        return "No real solutions"\n    x1 = (-b + math.sqrt(disc)) / (2*a)\n    x2 = (-b - math.sqrt(disc)) / (2*a)\n    return x1, x2\n\nprint("x²-5x+6:", solve_quadratic(1, -5, 6))\nprint("x²+2x-8:", solve_quadratic(1, 2, -8))\nprint("x²+x+1:", solve_quadratic(1, 1, 1))`,
    checkOutput: (o) => o.includes('3.0') && o.includes('2.0') && o.includes('No real'),
    expectedHint: 'x²-5x+6: (3.0, 2.0)\nx²+2x-8: (2.0, -4.0)\nx²+x+1: No real solutions',
    hints: [
      'disc = b**2 - 4*a*c — the discriminant',
      'Divide by (2*a) for both solutions',
      'c = -8 for the second equation, c = 1 for the third',
    ],
  },
  {
    id: 'crt-m-5-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Number Theory',
    unitIndex: 1,
    title: 'Greatest common divisor (GCD)',
    emoji: '🔑',
    realWorldUse: 'Used in: simplifying fractions, cryptography (RSA key generation), music theory',
    concept: `The **GCD** of two numbers is the largest number that divides both evenly.\n\nGCD(12, 8) = 4, because 4 is the biggest number that divides both 12 and 8.\n\n**Euclid's algorithm** (ancient Greek, ~300 BC):\n\`\`\`python\ndef gcd(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a\n\`\`\`\n\nThis is one of the oldest algorithms still in use today!`,
    example: `def gcd(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a\n\nprint(gcd(48, 18))  # 6\nprint(gcd(100, 75)) # 25`,
    challenge: `Implement \`gcd(a, b)\` using Euclid's algorithm.\nFind GCD of:\n1. 56 and 42\n2. 144 and 60\n3. 17 and 13 (both prime — what should the answer be?)`,
    starterCode: `def gcd(a, b):\n    while b != ___:\n        a, b = b, a % ___\n    return a\n\nprint("GCD(56,42):", gcd(56, 42))\nprint("GCD(144,60):", gcd(144, 60))\nprint("GCD(17,13):", gcd(17, 13))`,
    solutionCode: `def gcd(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a\n\nprint("GCD(56,42):", gcd(56, 42))\nprint("GCD(144,60):", gcd(144, 60))\nprint("GCD(17,13):", gcd(17, 13))`,
    checkOutput: (o) => o.includes('14') && o.includes('12') && o.includes('1'),
    expectedHint: 'GCD(56,42): 14\nGCD(144,60): 12\nGCD(17,13): 1',
    hints: [
      'while b != 0 — keep going until b is zero',
      'a, b = b, a % b — swap and take remainder',
      'Two primes always have GCD = 1',
    ],
  },
  {
    id: 'crt-m-6-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Statistics',
    unitIndex: 1,
    title: 'Standard deviation',
    emoji: '📉',
    realWorldUse: 'Used in: quality control, finance risk analysis, scientific experiments, AI/ML',
    concept: `**Standard deviation** measures how spread out data is from the mean.\n\nSteps:\n1. Find the mean\n2. For each value: subtract mean, square the result\n3. Average those squared differences\n4. Take the square root\n\n\`\`\`python\nimport math\n\ndef std_dev(data):\n    mean = sum(data) / len(data)\n    squared_diffs = [(x - mean)**2 for x in data]\n    variance = sum(squared_diffs) / len(data)\n    return math.sqrt(variance)\n\`\`\``,
    example: `import math\n\ndef std_dev(data):\n    mean = sum(data) / len(data)\n    squared_diffs = [(x - mean)**2 for x in data]\n    variance = sum(squared_diffs) / len(data)\n    return math.sqrt(variance)\n\nprint(std_dev([2, 4, 4, 4, 5, 5, 7, 9]))`,
    challenge: `Write a \`std_dev(data)\` function.\nCalculate standard deviation for:\n1. [10, 10, 10, 10, 10] (all same — what should the answer be?)\n2. [1, 2, 3, 4, 5]\n3. [5, 10, 15, 20, 25]`,
    starterCode: `import math\n\ndef std_dev(data):\n    mean = sum(data) / ___(data)\n    squared_diffs = [(x - mean)**2 for x in ___]\n    variance = sum(squared_diffs) / len(data)\n    return math.sqrt(___)\n\nprint(std_dev([10, 10, 10, 10, 10]))\nprint(std_dev([1, 2, 3, 4, 5]))\nprint(std_dev([5, 10, 15, 20, 25]))`,
    solutionCode: `import math\n\ndef std_dev(data):\n    mean = sum(data) / len(data)\n    squared_diffs = [(x - mean)**2 for x in data]\n    variance = sum(squared_diffs) / len(data)\n    return math.sqrt(variance)\n\nprint(std_dev([10, 10, 10, 10, 10]))\nprint(std_dev([1, 2, 3, 4, 5]))\nprint(std_dev([5, 10, 15, 20, 25]))`,
    checkOutput: (o) => o.includes('0') && o.includes('1.') && o.includes('7.'),
    expectedHint: '0.0\n1.414...\n7.071...',
    hints: [
      'Use len(data) for the count',
      'Iterate over data in the list comprehension',
      'Take sqrt of variance',
      'All same values = 0 standard deviation',
    ],
  },
  {
    id: 'crt-m-7-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Geometry',
    unitIndex: 1,
    title: 'Distance between two points',
    emoji: '📍',
    realWorldUse: 'Used in: GPS navigation, game collision, map apps, drone routing',
    concept: `The **distance formula** between two points (x₁, y₁) and (x₂, y₂):\n\n**d = √((x₂ - x₁)² + (y₂ - y₁)²)**\n\nThis is just Pythagoras theorem applied to coordinates!\n\n\`\`\`python\nimport math\n\ndef distance(x1, y1, x2, y2):\n    return math.sqrt((x2-x1)**2 + (y2-y1)**2)\n\`\`\``,
    example: `import math\n\ndef distance(x1, y1, x2, y2):\n    return math.sqrt((x2-x1)**2 + (y2-y1)**2)\n\nprint(distance(0, 0, 3, 4))  # 5.0 — the 3-4-5 triangle!`,
    challenge: `Write a \`distance(x1, y1, x2, y2)\` function.\nCalculate distance between:\n1. (0, 0) and (3, 4)\n2. (1, 1) and (4, 5)\n3. (-2, 3) and (5, -1)`,
    starterCode: `import math\n\ndef distance(x1, y1, x2, y2):\n    return math.sqrt((x2-___)**2 + (y2-___)**2)\n\nprint(distance(0, 0, 3, 4))\nprint(distance(1, 1, 4, 5))\nprint(distance(-2, 3, 5, ___))`,
    solutionCode: `import math\n\ndef distance(x1, y1, x2, y2):\n    return math.sqrt((x2-x1)**2 + (y2-y1)**2)\n\nprint(distance(0, 0, 3, 4))\nprint(distance(1, 1, 4, 5))\nprint(distance(-2, 3, 5, -1))`,
    checkOutput: (o) => o.includes('5.0') && o.includes('5.0') && o.includes('8.'),
    expectedHint: '5.0\n5.0\n8.062...',
    hints: [
      'Subtract x1 from x2, and y1 from y2',
      'Square both differences, add them, take sqrt',
      'The third point: y2 = -1',
    ],
  },
  {
    id: 'crt-m-8-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Probability',
    unitIndex: 0,
    title: 'Simulate coin flips',
    emoji: '🪙',
    realWorldUse: 'Used in: Monte Carlo simulations, A/B testing, risk analysis, game design',
    concept: `You can **simulate probability** with code! Python's \`random\` module generates random numbers.\n\n\`\`\`python\nimport random\n\n# Simulate one coin flip: 0 = heads, 1 = tails\nflip = random.randint(0, 1)\n\`\`\`\n\nBy running thousands of simulations, you can estimate probabilities — this is called a **Monte Carlo simulation**.`,
    example: `import random\n\nflips = 1000\nheads = 0\nfor _ in range(flips):\n    if random.randint(0, 1) == 0:\n        heads += 1\n\nprint("Heads:", heads, "out of", flips)\nprint("Probability:", heads / flips)`,
    challenge: `Simulate **10000 coin flips** and calculate the probability of heads.\nIt should be close to 0.5 (50%).`,
    starterCode: `import random\n\nflips = 10000\nheads = ___\nfor _ in range(___):\n    if random.randint(0, 1) == 0:\n        heads += ___\n\nprint("Heads:", heads)\nprint("Probability:", heads / ___)`,
    solutionCode: `import random\n\nflips = 10000\nheads = 0\nfor _ in range(flips):\n    if random.randint(0, 1) == 0:\n        heads += 1\n\nprint("Heads:", heads)\nprint("Probability:", heads / flips)`,
    checkOutput: (o) => o.includes('0.4') || o.includes('0.5') || o.includes('0.6'),
    expectedHint: 'Heads: ~5000\nProbability: ~0.5',
    hints: [
      'Start heads at 0',
      'Loop range(flips) — 10000 times',
      'Add 1 to heads each time it\'s 0',
      'Divide heads by flips for probability',
    ],
  },
  {
    id: 'crt-m-9-1',
    tier: 'CREATOR',
    subject: 'math',
    unit: 'Number Theory',
    unitIndex: 2,
    title: 'Sieve of Eratosthenes',
    emoji: '🏛️',
    realWorldUse: 'Used in: cryptography, prime number generation, competitive programming',
    concept: `The **Sieve of Eratosthenes** (200 BC!) finds ALL primes up to N efficiently.\n\nAlgorithm:\n1. Create a list of numbers 2 to N\n2. Start with 2 — mark all its multiples as NOT prime\n3. Move to the next unmarked number, mark its multiples\n4. Repeat until you've checked all numbers up to √N\n\nTime complexity: **O(n log log n)** — much faster than checking each number!\n\n\`\`\`python\ndef sieve(n):\n    is_prime = [True] * (n + 1)\n    is_prime[0] = is_prime[1] = False\n    for i in range(2, int(n**0.5) + 1):\n        if is_prime[i]:\n            for j in range(i*i, n + 1, i):\n                is_prime[j] = False\n    return [i for i in range(n + 1) if is_prime[i]]\n\`\`\``,
    example: `def sieve(n):\n    is_prime = [True] * (n + 1)\n    is_prime[0] = is_prime[1] = False\n    for i in range(2, int(n**0.5) + 1):\n        if is_prime[i]:\n            for j in range(i*i, n + 1, i):\n                is_prime[j] = False\n    return [i for i in range(n + 1) if is_prime[i]]\n\nprint(sieve(30))`,
    challenge: `Implement the Sieve of Eratosthenes.\nFind all primes up to **100**.\nHow many primes are there? Print the count.`,
    starterCode: `def sieve(n):\n    is_prime = [True] * (n + 1)\n    is_prime[0] = is_prime[1] = ___\n    for i in range(2, int(n**0.5) + 1):\n        if is_prime[i]:\n            for j in range(i*i, n + 1, i):\n                is_prime[j] = ___\n    return [i for i in range(n + 1) if is_prime[i]]\n\nprimes = sieve(100)\nprint("Primes up to 100:", primes)\nprint("Count:", len(___))`,
    solutionCode: `def sieve(n):\n    is_prime = [True] * (n + 1)\n    is_prime[0] = is_prime[1] = False\n    for i in range(2, int(n**0.5) + 1):\n        if is_prime[i]:\n            for j in range(i*i, n + 1, i):\n                is_prime[j] = False\n    return [i for i in range(n + 1) if is_prime[i]]\n\nprimes = sieve(100)\nprint("Primes up to 100:", primes)\nprint("Count:", len(primes))`,
    checkOutput: (o) => o.includes('25') && o.includes('97'),
    expectedHint: '25 primes up to 100, including 2, 3, 5, 7... 97',
    hints: [
      '0 and 1 are not prime: set to False',
      'Mark multiples as False: is_prime[j] = False',
      'Return len(primes) for the count — there are 25',
    ],
  },
]

export const ALL_LESSONS: Lesson[] = [
  ...EXPLORER_LESSONS,
  ...BUILDER_LESSONS,
  ...CREATOR_LESSONS,
]

export function getLessonsForTier(tier: LessonTier): Lesson[] {
  return ALL_LESSONS.filter((l) => l.tier === tier)
}

export function getLessonById(id: string): Lesson | undefined {
  return ALL_LESSONS.find((l) => l.id === id)
}

export function getUnitsForTier(tier: LessonTier): string[] {
  const lessons = getLessonsForTier(tier)
  return [...new Set(lessons.map((l) => l.unit))]
}

export function getCodingLessonsForTier(tier: LessonTier): Lesson[] {
  return getLessonsForTier(tier).filter((l) => l.subject === 'coding')
}

export function getMathLessonsForTier(tier: LessonTier): Lesson[] {
  return getLessonsForTier(tier).filter((l) => l.subject === 'math')
}
